"""Generates per-developer claudebox instances from developers.json: one
claudebox container (own OAuth token, own auth volume) and one LiteLLM
model per Claude tier per developer, so each person's traffic runs against
their own subscription's rate limits instead of one shared one.

Run after editing developers.json, before `docker compose build`:
    python3 docker/generate_developers.py

Writes docker-compose.developers.yml and config/litellm_config.developers.yaml.
Use both alongside the base stack:
    docker compose -f docker-compose.yml -f docker-compose.developers.yml up -d --build
"""
import json
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TIERS = ["haiku", "sonnet", "opus", "opusplan"]
PRICING_REF = {
    "haiku": "claude-haiku-4-5",
    "sonnet": "claude-sonnet-5",
    "opus": "claude-opus-5",
    "opusplan": "claude-opus-5",  # hybrid mode, no fixed price; opus as upper bound
}
SLUG_RE = re.compile(r"^[a-z0-9][a-z0-9-]*$")

developers_path = os.path.join(ROOT, "developers.json")
if not os.path.exists(developers_path):
    sys.exit(
        "developers.json not found. Copy developers.json.example to "
        "developers.json and fill in your team, then rerun this script."
    )

with open(developers_path) as f:
    developers = json.load(f)["developers"]

slugs = set()
for dev in developers:
    slug = dev["slug"]
    if not SLUG_RE.match(slug):
        sys.exit(f"invalid slug '{slug}': lowercase letters, digits, hyphens only")
    if slug in slugs:
        sys.exit(f"duplicate slug '{slug}'")
    slugs.add(slug)

compose_services = []
compose_volumes = []
model_entries = []

for dev in developers:
    slug = dev["slug"]
    env_suffix = slug.upper().replace("-", "_")
    compose_services.append(f"""\
  claudebox-{slug}:
    image: psyb0t/claudebox:v2.3.9
    restart: unless-stopped
    environment:
      CLAUDEBOX_API_MODE: "1"
      CLAUDEBOX_API_MODE_TOKEN: ${{CLAUDEBOX_API_MODE_TOKEN}}
      CLAUDE_CODE_OAUTH_TOKEN: ${{CLAUDE_CODE_OAUTH_TOKEN_{env_suffix}}}
      CLAUDEBOX_GIT_NAME: {json.dumps(dev["name"])}
      CLAUDEBOX_GIT_EMAIL: {json.dumps(dev["git_email"])}
    volumes:
      - claude_auth_{slug}:/home/aicode/.claude
      - ./ssh:/home/aicode/.ssh/claudebox:ro
      - ./workspaces:/workspace
    security_opt:
      - no-new-privileges:true
    mem_limit: 2g
    cpus: 1
    pids_limit: 256
    networks:
      - backend
""")
    compose_volumes.append(f"  claude_auth_{slug}:\n")

    for tier in TIERS:
        model_entries.append({
            "model_name": f"{tier}-{slug}",
            "litellm_params": {
                "model": f"openai/{tier}",
                "api_base": f"http://claudebox-{slug}:8080/openai/v1",
                "api_key": "os.environ/CLAUDEBOX_API_MODE_TOKEN",
            },
            "model_info": {"pricing_ref": PRICING_REF[tier]},
        })

compose_out = (
    "# Generated by docker/generate_developers.py from developers.json. Don't hand-edit.\n"
    "services:\n" + ("".join(compose_services) if compose_services else "  {}\n") +
    "volumes:\n" + ("".join(compose_volumes) if compose_volumes else "  {}\n")
)
with open(os.path.join(ROOT, "docker-compose.developers.yml"), "w") as f:
    f.write(compose_out)

# Hand-written, not yaml.dump, so this stays dependency-free on the host
# (see docker/render_pricing.py for the parse+merge step, which runs inside
# the litellm image where PyYAML is already installed).
lines = ["# Generated by docker/generate_developers.py from developers.json. Don't hand-edit.",
          "model_list:"]
if not model_entries:
    lines[-1] += " []"
for entry in model_entries:
    lp = entry["litellm_params"]
    lines.append(f"  - model_name: {entry['model_name']}")
    lines.append("    litellm_params:")
    lines.append(f"      model: {lp['model']}")
    lines.append(f"      api_base: {lp['api_base']}")
    lines.append(f"      api_key: {lp['api_key']}")
    lines.append("    model_info:")
    lines.append(f"      pricing_ref: {entry['model_info']['pricing_ref']}")
with open(os.path.join(ROOT, "config", "litellm_config.developers.yaml"), "w") as f:
    f.write("\n".join(lines) + "\n")

print(f"Generated {len(developers)} developer(s): {', '.join(sorted(slugs))}")
print("Required .env vars: " + ", ".join(
    f"CLAUDE_CODE_OAUTH_TOKEN_{d['slug'].upper().replace('-', '_')}" for d in developers
))
